import './globals.css'
import {  Urbanist } from 'next/font/google'
import NavBar from './components/NavBar';
import {Analytics} from '@vercel/analytics/react'

const manrope = Urbanist({ subsets: ['latin'],
 })

export const metadata = {
  title: 'Portfolio Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body>
        <main className={manrope.className}>
          <NavBar/>
          {children}
          <Analytics />
        </main>
      </body>
    </html>
  )
}
